spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/todo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.kienminh.todobackend: DEBUG

server:
  port: 8081
